<?php

define('QUESTION_ADD_QUESTION_ITEMID', 107);
define('QUESTION_CATEGORY_ITEMID', 103);
define('QUESTION_LIST_MY_QUESTIONS_ITEMID', 109);
define('QUESTION_TAGS_ITEMID', 100);
define('QUESTION_DEFAULT_CATEGORY', 8);